Add fusion runtime setting to logs
fusion-oss/fusion-connect pull request #82
Opened 2023-03-23 22:13 UTC by javierscope

2023-04-11 00:29 UTC, amit-petkar requested changes

2023-04-11 00:29 UTC, amit-petkar commented on src/main/java/com/scoperetail/fusion/FusionApplication.java
> +  private static final Logger log = LoggerFactory.getLogger(FusionApplication.class);
create separate component. No code in FusionApplication class.

2023-04-11 00:29 UTC, amit-petkar commented on src/main/java/com/scoperetail/fusion/FusionApplication.java
> +  private static List<String> filter = new ArrayList<>(1);
@Value

Add property under fusion config. Please talk to Ravi.

2023-04-11 00:29 UTC, amit-petkar commented on src/main/java/com/scoperetail/fusion/FusionApplication.java
> +      filter = Arrays.asList(logFilter.split(","));
Split has to be done in @Value.

2023-04-11 00:29 UTC, amit-petkar commented on src/main/java/com/scoperetail/fusion/FusionApplication.java
> +      if(currentEnv.contains(f)){
instead of contains - use regex for matching.

2023-04-11 00:29 UTC, amit-petkar commented on src/main/java/com/scoperetail/fusion/FusionApplication.java
> +  private boolean isFiltered(final String currentEnv) {
currentEnv is misleading. Use readable names.

2023-04-11 00:29 UTC, amit-petkar commented on src/main/java/com/scoperetail/fusion/FusionApplication.java
> +    for(String f: filter) {
Instead of iteration can we keep all string in single regex and match against that? This will help us get rid of this method.

2023-04-11 00:29 UTC, amit-petkar commented on src/main/java/com/scoperetail/fusion/FusionApplication.java
> +    log.info("FusionCCM: {}", new JSONObject(ccmProperties).toString());
fusion config is hierarchical. By keeping every property in hash map will not be readable. I hope we are printing fusion config object values. 

Where is the pull request for the CCM?

2023-04-11 00:29 UTC, amit-petkar commented on src/main/java/com/scoperetail/fusion/FusionApplication.java
> +    Map<String, Object> ccmProperties = new HashMap<>();
remove this and use the same jsonObject instead.

2023-04-11 00:29 UTC, amit-petkar commented on src/test/resources/DOOR_STATUS/valid.json
> +  ]
Get rid of this change.

2023-04-11 00:29 UTC, amit-petkar commented on src/main/java/com/scoperetail/fusion/FusionApplication.java
> +    final Environment env = event.getApplicationContext()
@Autowired
private Environment environment;

Use separate component

2023-04-11 00:29 UTC, amit-petkar commented on src/main/java/com/scoperetail/fusion/FusionApplication.java
> +    for(String f: filter) {
what if filter is empty?

2023-04-11 00:29 UTC, amit-petkar commented on src/main/java/com/scoperetail/fusion/FusionApplication.java
> +      .filter(this::isFiltered)
can we collect to a map directly?

2023-04-11 17:04 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/FusionApplication.java
> +    for(String f: filter) {
If filter is empty, no properties are printed in log.

2023-04-11 17:42 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/FusionApplication.java
> +  private static final Logger log = LoggerFactory.getLogger(FusionApplication.class);
created

2023-04-11 17:42 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/FusionApplication.java
> +  private static List<String> filter = new ArrayList<>(1);
Added

2023-04-11 17:58 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/FusionApplication.java
> +    final Environment env = event.getApplicationContext()
done

2023-04-13 14:52 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/FusionApplication.java
> +      filter = Arrays.asList(logFilter.split(","));
Done

2023-04-13 14:52 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/FusionApplication.java
> +      if(currentEnv.contains(f)){
Check

2023-04-13 14:52 UTC, javierscope commented on src/test/resources/DOOR_STATUS/valid.json
> +  ]
Done

2023-04-14 13:06 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/FusionApplication.java
> +    for(String f: filter) {
Done

2023-04-14 13:06 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/FusionApplication.java
> +    log.info("FusionCCM: {}", new JSONObject(ccmProperties).toString());
Sent

2023-04-18 13:51 UTC, closed without merging